[package]
name = "xkcd_api"
version = "0.1.0"
authors = ["Galen G <github@mastrchef.rocks>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
